# DataSource Config
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.3.17:3306/mybatis
        schema: classpath:db/schema-h2.sql
        data: classpath:db/data-h2.sql
        initialization-mode: ALWAYS
        username: ycy
        password: xx5320980.
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            initial-size: 8
            min-idle: 1
            max-active: 20
            max-wait: 60000
            time-between-eviction-runsMillis: 60000
            min-evictable-idle-timeMillis: 300000
            validation-query: select 'x' FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            use-global-data-source-stat: true
            stat-view-servlet:
                url-pattern: /druid/*
                allow: 127.0.0.1,192.168.3.17,*
                login-username: admin
                login-password: 123456

# Logger Config
logging:
    level:
        com.baomidou.mybatisplus.samples.quickstart: debug
